"""Type stubs for the compiled ``rscopulas._rscopulas`` extension.

These are hand-written and must be kept in sync with
``crates/rscopulas-python/src/lib.rs``; ``python/tests/test_metadata.py``
checks that every public name exported by the extension is declared here.
"""

from __future__ import annotations

from typing import Any, Sequence

import numpy as np
import numpy.typing as npt

__version__: str

_FloatArray = npt.NDArray[np.float64]
_Seed = int | None

class RscopulasError(Exception):
    """Base class for every exception raised by rscopulas."""

class InvalidInputError(RscopulasError, ValueError):
    """Input data or arguments failed validation."""

class NonPrefixConditioningError(InvalidInputError):
    """Known columns are not a diagonal prefix of ``variable_order``."""

class ModelFitError(RscopulasError):
    """A fitting or estimation routine failed to produce a valid model."""

class NumericalError(RscopulasError):
    """A numerical routine produced an invalid result."""

class BackendError(RscopulasError):
    """The requested execution backend is unavailable or failed."""

class InternalError(RscopulasError):
    """An internal Rust panic was caught at the Python boundary."""

class _FitDiagnostics:
    @property
    def loglik(self) -> float: ...
    @property
    def aic(self) -> float: ...
    @property
    def bic(self) -> float: ...
    @property
    def converged(self) -> bool: ...
    @property
    def n_iter(self) -> int: ...
    @property
    def likelihood_kind(self) -> str: ...

class _GaussianCopula:
    def __init__(self, payload: str) -> None: ...
    @staticmethod
    def from_params(correlation: _FloatArray) -> _GaussianCopula: ...
    @staticmethod
    def fit(
        data: _FloatArray, clip_eps: float = ..., max_iter: int = ...
    ) -> tuple[_GaussianCopula, _FitDiagnostics]: ...
    @staticmethod
    def from_json(payload: str) -> _GaussianCopula: ...
    def to_json(self) -> str: ...
    @property
    def dim(self) -> int: ...
    @property
    def family(self) -> str: ...
    @property
    def correlation(self) -> _FloatArray: ...
    def log_pdf(self, data: _FloatArray, clip_eps: float = ...) -> _FloatArray: ...
    def sample(self, n: int, seed: _Seed = ...) -> _FloatArray: ...
    def __reduce__(self) -> tuple[type[_GaussianCopula], tuple[str]]: ...
    def __copy__(self) -> _GaussianCopula: ...
    def __deepcopy__(self, memo: dict[int, Any]) -> _GaussianCopula: ...
    def __eq__(self, other: object) -> bool: ...

class _StudentTCopula:
    def __init__(self, payload: str) -> None: ...
    @staticmethod
    def from_params(correlation: _FloatArray, degrees_of_freedom: float) -> _StudentTCopula: ...
    @staticmethod
    def fit(
        data: _FloatArray, clip_eps: float = ..., max_iter: int = ...
    ) -> tuple[_StudentTCopula, _FitDiagnostics]: ...
    @staticmethod
    def from_json(payload: str) -> _StudentTCopula: ...
    def to_json(self) -> str: ...
    @property
    def dim(self) -> int: ...
    @property
    def family(self) -> str: ...
    @property
    def correlation(self) -> _FloatArray: ...
    @property
    def degrees_of_freedom(self) -> float: ...
    def log_pdf(self, data: _FloatArray, clip_eps: float = ...) -> _FloatArray: ...
    def sample(self, n: int, seed: _Seed = ...) -> _FloatArray: ...
    def __reduce__(self) -> tuple[type[_StudentTCopula], tuple[str]]: ...
    def __copy__(self) -> _StudentTCopula: ...
    def __deepcopy__(self, memo: dict[int, Any]) -> _StudentTCopula: ...
    def __eq__(self, other: object) -> bool: ...

class _ClaytonCopula:
    def __init__(self, payload: str) -> None: ...
    @staticmethod
    def from_params(dim: int, theta: float) -> _ClaytonCopula: ...
    @staticmethod
    def fit(
        data: _FloatArray, clip_eps: float = ..., max_iter: int = ...
    ) -> tuple[_ClaytonCopula, _FitDiagnostics]: ...
    @staticmethod
    def from_json(payload: str) -> _ClaytonCopula: ...
    def to_json(self) -> str: ...
    @property
    def dim(self) -> int: ...
    @property
    def family(self) -> str: ...
    @property
    def theta(self) -> float: ...
    def log_pdf(self, data: _FloatArray, clip_eps: float = ...) -> _FloatArray: ...
    def sample(self, n: int, seed: _Seed = ...) -> _FloatArray: ...
    def __reduce__(self) -> tuple[type[_ClaytonCopula], tuple[str]]: ...
    def __copy__(self) -> _ClaytonCopula: ...
    def __deepcopy__(self, memo: dict[int, Any]) -> _ClaytonCopula: ...
    def __eq__(self, other: object) -> bool: ...

class _FrankCopula:
    def __init__(self, payload: str) -> None: ...
    @staticmethod
    def from_params(dim: int, theta: float) -> _FrankCopula: ...
    @staticmethod
    def fit(
        data: _FloatArray, clip_eps: float = ..., max_iter: int = ...
    ) -> tuple[_FrankCopula, _FitDiagnostics]: ...
    @staticmethod
    def from_json(payload: str) -> _FrankCopula: ...
    def to_json(self) -> str: ...
    @property
    def dim(self) -> int: ...
    @property
    def family(self) -> str: ...
    @property
    def theta(self) -> float: ...
    def log_pdf(self, data: _FloatArray, clip_eps: float = ...) -> _FloatArray: ...
    def sample(self, n: int, seed: _Seed = ...) -> _FloatArray: ...
    def __reduce__(self) -> tuple[type[_FrankCopula], tuple[str]]: ...
    def __copy__(self) -> _FrankCopula: ...
    def __deepcopy__(self, memo: dict[int, Any]) -> _FrankCopula: ...
    def __eq__(self, other: object) -> bool: ...

class _GumbelCopula:
    def __init__(self, payload: str) -> None: ...
    @staticmethod
    def from_params(dim: int, theta: float) -> _GumbelCopula: ...
    @staticmethod
    def fit(
        data: _FloatArray, clip_eps: float = ..., max_iter: int = ...
    ) -> tuple[_GumbelCopula, _FitDiagnostics]: ...
    @staticmethod
    def from_json(payload: str) -> _GumbelCopula: ...
    def to_json(self) -> str: ...
    @property
    def dim(self) -> int: ...
    @property
    def family(self) -> str: ...
    @property
    def theta(self) -> float: ...
    def log_pdf(self, data: _FloatArray, clip_eps: float = ...) -> _FloatArray: ...
    def sample(self, n: int, seed: _Seed = ...) -> _FloatArray: ...
    def __reduce__(self) -> tuple[type[_GumbelCopula], tuple[str]]: ...
    def __copy__(self) -> _GumbelCopula: ...
    def __deepcopy__(self, memo: dict[int, Any]) -> _GumbelCopula: ...
    def __eq__(self, other: object) -> bool: ...

class _PairCopula:
    def __init__(self, payload: str) -> None: ...
    @staticmethod
    def from_spec(
        family: str,
        parameters: Sequence[float] | None = ...,
        rotation: str = ...,
        state: dict[str, Any] | None = ...,
    ) -> _PairCopula: ...
    @staticmethod
    def fit_tll(u1: _FloatArray, u2: _FloatArray, method: str = ...) -> _PairCopula: ...
    @staticmethod
    def from_khoudraji(
        first_family: str,
        second_family: str,
        shape_1: float,
        shape_2: float,
        first_parameters: Sequence[float] | None = ...,
        second_parameters: Sequence[float] | None = ...,
        rotation: str = ...,
        first_rotation: str = ...,
        second_rotation: str = ...,
    ) -> _PairCopula: ...
    @staticmethod
    def from_json(payload: str) -> _PairCopula: ...
    def to_json(self) -> str: ...
    @property
    def family(self) -> str: ...
    @property
    def rotation(self) -> str: ...
    @property
    def parameters(self) -> list[float]: ...
    @property
    def spec(self) -> dict[str, Any]: ...
    @property
    def dim(self) -> int: ...
    def log_pdf(self, u1: _FloatArray, u2: _FloatArray, clip_eps: float = ...) -> _FloatArray: ...
    def cond_first_given_second(
        self, u1: _FloatArray, u2: _FloatArray, clip_eps: float = ...
    ) -> _FloatArray: ...
    def cond_second_given_first(
        self, u1: _FloatArray, u2: _FloatArray, clip_eps: float = ...
    ) -> _FloatArray: ...
    def inv_first_given_second(
        self, p: _FloatArray, u2: _FloatArray, clip_eps: float = ...
    ) -> _FloatArray: ...
    def inv_second_given_first(
        self, u1: _FloatArray, p: _FloatArray, clip_eps: float = ...
    ) -> _FloatArray: ...
    def __reduce__(self) -> tuple[type[_PairCopula], tuple[str]]: ...
    def __copy__(self) -> _PairCopula: ...
    def __deepcopy__(self, memo: dict[int, Any]) -> _PairCopula: ...
    def __eq__(self, other: object) -> bool: ...

class _VineCopula:
    def __init__(self, payload: str) -> None: ...
    @staticmethod
    def from_trees(
        kind: str, trees: Sequence[dict[str, Any]], truncation_level: int | None
    ) -> _VineCopula: ...
    @staticmethod
    def gaussian_c_vine(order: Sequence[int], correlation: _FloatArray) -> _VineCopula: ...
    @staticmethod
    def gaussian_d_vine(order: Sequence[int], correlation: _FloatArray) -> _VineCopula: ...
    @staticmethod
    def fit_c(
        data: _FloatArray,
        family_set: Sequence[str] | None = ...,
        include_rotations: bool = ...,
        criterion: str = ...,
        truncation_level: int | None = ...,
        independence_threshold: float | None = ...,
        independence_test_level: float | None = ...,
        clip_eps: float = ...,
        max_iter: int = ...,
        order: Sequence[int] | None = ...,
        tree_algorithm: str = ...,
        tree_criterion: str = ...,
        select_trunc_lvl: bool = ...,
        rng_seed: _Seed = ...,
    ) -> tuple[_VineCopula, _FitDiagnostics]: ...
    @staticmethod
    def fit_d(
        data: _FloatArray,
        family_set: Sequence[str] | None = ...,
        include_rotations: bool = ...,
        criterion: str = ...,
        truncation_level: int | None = ...,
        independence_threshold: float | None = ...,
        independence_test_level: float | None = ...,
        clip_eps: float = ...,
        max_iter: int = ...,
        order: Sequence[int] | None = ...,
        tree_algorithm: str = ...,
        tree_criterion: str = ...,
        select_trunc_lvl: bool = ...,
        rng_seed: _Seed = ...,
    ) -> tuple[_VineCopula, _FitDiagnostics]: ...
    @staticmethod
    def fit_r(
        data: _FloatArray,
        family_set: Sequence[str] | None = ...,
        include_rotations: bool = ...,
        criterion: str = ...,
        truncation_level: int | None = ...,
        independence_threshold: float | None = ...,
        independence_test_level: float | None = ...,
        clip_eps: float = ...,
        max_iter: int = ...,
        tree_algorithm: str = ...,
        tree_criterion: str = ...,
        select_trunc_lvl: bool = ...,
        rng_seed: _Seed = ...,
    ) -> tuple[_VineCopula, _FitDiagnostics]: ...
    @staticmethod
    def from_json(payload: str) -> _VineCopula: ...
    def to_json(self) -> str: ...
    @property
    def dim(self) -> int: ...
    @property
    def family(self) -> str: ...
    @property
    def structure_kind(self) -> str: ...
    @property
    def truncation_level(self) -> int | None: ...
    def order(self) -> list[int]: ...
    def pair_parameters(self) -> list[float]: ...
    def structure_info(self) -> dict[str, Any]: ...
    def trees(self) -> list[dict[str, Any]]: ...
    def log_pdf(self, data: _FloatArray, clip_eps: float = ...) -> _FloatArray: ...
    def sample(self, n: int, seed: _Seed = ...) -> _FloatArray: ...
    def variable_order(self) -> list[int]: ...
    def rosenblatt(self, data: _FloatArray) -> _FloatArray: ...
    def inverse_rosenblatt(self, data: _FloatArray) -> _FloatArray: ...
    def rosenblatt_prefix(self, data: _FloatArray, col_limit: int) -> _FloatArray: ...
    def __reduce__(self) -> tuple[type[_VineCopula], tuple[str]]: ...
    def __copy__(self) -> _VineCopula: ...
    def __deepcopy__(self, memo: dict[int, Any]) -> _VineCopula: ...
    def __eq__(self, other: object) -> bool: ...

class _HierarchicalArchimedeanCopula:
    def __init__(self, payload: str) -> None: ...
    @staticmethod
    def from_tree(tree: int | dict[str, Any]) -> _HierarchicalArchimedeanCopula: ...
    @staticmethod
    def fit(
        data: _FloatArray,
        tree: int | dict[str, Any] | None = ...,
        family_set: Sequence[str] | None = ...,
        structure_method: str = ...,
        fit_method: str = ...,
        collapse_eps: float = ...,
        mc_samples: int = ...,
        allow_experimental: bool = ...,
        clip_eps: float = ...,
        max_iter: int = ...,
    ) -> tuple[_HierarchicalArchimedeanCopula, _FitDiagnostics]: ...
    @staticmethod
    def from_json(payload: str) -> _HierarchicalArchimedeanCopula: ...
    def to_json(self) -> str: ...
    @property
    def dim(self) -> int: ...
    @property
    def family(self) -> str: ...
    @property
    def is_exact(self) -> bool: ...
    @property
    def exact_loglik(self) -> bool: ...
    @property
    def used_smle(self) -> bool: ...
    @property
    def mc_samples(self) -> int: ...
    @property
    def structure_method(self) -> str: ...
    @property
    def fit_method(self) -> str: ...
    def tree(self) -> int | dict[str, Any]: ...
    def leaf_order(self) -> list[int]: ...
    def parameters(self) -> list[float]: ...
    def families(self) -> list[str]: ...
    def log_pdf(self, data: _FloatArray, clip_eps: float = ...) -> _FloatArray: ...
    def composite_log_pdf(self, data: _FloatArray, clip_eps: float = ...) -> _FloatArray: ...
    def sample(self, n: int, seed: _Seed = ...) -> _FloatArray: ...
    def __reduce__(self) -> tuple[type[_HierarchicalArchimedeanCopula], tuple[str]]: ...
    def __copy__(self) -> _HierarchicalArchimedeanCopula: ...
    def __deepcopy__(self, memo: dict[int, Any]) -> _HierarchicalArchimedeanCopula: ...
    def __eq__(self, other: object) -> bool: ...

class _FactorCopula:
    def __init__(self, payload: str) -> None: ...
    @staticmethod
    def from_links(
        links: Sequence[dict[str, Any]],
        quadrature_nodes: int = ...,
        *,
        adaptive_quadrature: bool = ...,
        quadrature_max_nodes: int = ...,
        quadrature_rel_tol: float = ...,
    ) -> _FactorCopula: ...
    @staticmethod
    def fit(
        data: _FloatArray,
        family_set: Sequence[str] | None = ...,
        include_rotations: bool = ...,
        criterion: str = ...,
        quadrature_nodes: int = ...,
        refine_iterations: int = ...,
        joint_polish_cycles: int = ...,
        joint_polish_rel_tol: float = ...,
        layout: str = ...,
        clip_eps: float = ...,
        max_iter: int = ...,
        adaptive_quadrature: bool = ...,
        quadrature_max_nodes: int = ...,
        quadrature_rel_tol: float = ...,
    ) -> tuple[_FactorCopula, _FitDiagnostics, list[float]]: ...
    @staticmethod
    def from_json(payload: str) -> _FactorCopula: ...
    def to_json(self) -> str: ...
    @property
    def dim(self) -> int: ...
    @property
    def family(self) -> str: ...
    @property
    def num_factors(self) -> int: ...
    @property
    def quadrature_nodes(self) -> int: ...
    @property
    def adaptive_quadrature(self) -> bool: ...
    @property
    def quadrature_max_nodes(self) -> int: ...
    @property
    def quadrature_rel_tol(self) -> float: ...
    @property
    def layout(self) -> str: ...
    def links(self) -> list[dict[str, Any]]: ...
    def log_pdf(self, data: _FloatArray, clip_eps: float = ...) -> _FloatArray: ...
    def sample(self, n: int, seed: _Seed = ...) -> _FloatArray: ...
    def __reduce__(self) -> tuple[type[_FactorCopula], tuple[str]]: ...
    def __copy__(self) -> _FactorCopula: ...
    def __deepcopy__(self, memo: dict[int, Any]) -> _FactorCopula: ...
    def __eq__(self, other: object) -> bool: ...

def uniform_matrix(n: int, d: int, seed: _Seed = ...) -> _FloatArray: ...
