//! Cross-validation of the pair-copula *fitter* against VineCopula's
//! `BiCopEst(method = "mle")`.
//!
//! Fixtures live in `fixtures/reference/fits/v1/pair_fit_*.json` and are
//! generated by `scripts/reference/generate_fit_fixtures.R`. Every fixture
//! stores `n = 2000` observations simulated from a known family/rotation with
//! `BiCopSim`, R's maximum-likelihood estimate, its Hessian-based standard
//! errors, R's log-likelihood at that estimate and the implied Kendall tau.
//!
//! For each case two independent tests run:
//!
//! * `kernel_at_r_estimate::*` — evaluating the Rust density at **R's**
//!   estimate reproduces R's log-likelihood to `1e-6` (absolute, on the sum
//!   over 2000 points). This checks the density kernels and the
//!   family/rotation/parameter mapping and must pass regardless of the
//!   fitter.
//! * `fitter_matches_r_mle::*` — fitting the *same* family with
//!   `fit_pair_copula` (rotation fixed to the fixture's, no family or
//!   rotation selection) must (a) reach a log-likelihood no more than `0.5`
//!   nats below R's MLE, and (b) land within `max(3 * SE_j, 0.02)` of R's
//!   estimate for every parameter `j`, where
//!   `SE_j = sqrt([I_obs(theta_R)^{-1}]_{jj})` is the
//!   inverse-observed-information standard error reported by
//!   `BiCopEst(se = TRUE)` (it scales like `n^{-1/2}`). Two MLEs on the
//!   same data should agree far more tightly than this; the budget only
//!   tolerates optimiser slack, not a different estimator.
//!
//! Rotation handling: `fit_pair_copula` with `include_rotations = false`
//! only ever fits `R0`, so for a rotated fixture the data are first mapped
//! into the base orientation with the *same* transform the crate uses
//! internally (`R90: (1 - u1, u2)`, `R180: (1 - u1, 1 - u2)`,
//! `R270: (u1, 1 - u2)`) and the fixture rotation is re-attached to the
//! fitted spec. The test then re-evaluates the rotated spec on the original
//! data and asserts it reproduces the fitter's own log-likelihood.
//!
//! Negative Frank: rscopulas cannot represent `theta < 0` yet. The kernel
//! test uses the identity `c_{-theta}(u, v) = c_theta(1 - u, v)` (Frank
//! `R90` with `|theta|`), which is exact, so the kernel check still runs. The
//! fitter test for that case accepts either a signed `theta` under `R0` or a
//! positive `theta` under `R90`/`R270` once negative dependence is supported.

use std::{fs, path::PathBuf};

use serde::Deserialize;

use rscopulas::paircopula::fit_pair_copula;
use rscopulas::{PairCopulaFamily, PairCopulaParams, PairCopulaSpec, Rotation, VineFitOptions};

const CLIP_EPS: f64 = 1e-12;
const LOGLIK_BUDGET: f64 = 0.5;
const KERNEL_TOL: f64 = 1e-6;
const PARAM_FLOOR: f64 = 0.02;

#[allow(dead_code)]
#[derive(Debug, Deserialize)]
struct Metadata {
    source_package: String,
    source_version: String,
}

#[allow(dead_code)]
#[derive(Debug, Deserialize)]
struct PairFitFixture {
    metadata: Metadata,
    case: String,
    family_code: i32,
    family: String,
    rotation: String,
    n: usize,
    true_params: Vec<f64>,
    r_par: f64,
    r_par2: f64,
    r_params: Vec<f64>,
    r_se: Vec<f64>,
    r_loglik: f64,
    r_loglik_reported: f64,
    r_tau: f64,
    empirical_tau: f64,
    u1: Vec<f64>,
    u2: Vec<f64>,
}

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/reference/fits/v1")
}

fn load_fixture(name: &str) -> PairFitFixture {
    let path = fixture_dir().join(name);
    let bytes =
        fs::read(&path).unwrap_or_else(|err| panic!("fixture {path:?} should exist: {err}"));
    let fixture: PairFitFixture =
        serde_json::from_slice(&bytes).expect("fixture should deserialize");
    assert_eq!(fixture.metadata.source_package, "VineCopula");
    assert_eq!(fixture.n, fixture.u1.len());
    assert_eq!(fixture.n, fixture.u2.len());
    fixture
}

fn parse_family(value: &str) -> PairCopulaFamily {
    match value {
        "Gaussian" => PairCopulaFamily::Gaussian,
        "StudentT" => PairCopulaFamily::StudentT,
        "Clayton" => PairCopulaFamily::Clayton,
        "Frank" => PairCopulaFamily::Frank,
        "Gumbel" => PairCopulaFamily::Gumbel,
        "Joe" => PairCopulaFamily::Joe,
        "Bb1" => PairCopulaFamily::Bb1,
        "Bb6" => PairCopulaFamily::Bb6,
        "Bb7" => PairCopulaFamily::Bb7,
        "Bb8" => PairCopulaFamily::Bb8,
        "Tawn1" => PairCopulaFamily::Tawn1,
        "Tawn2" => PairCopulaFamily::Tawn2,
        other => panic!("unexpected family {other}"),
    }
}

fn parse_rotation(value: &str) -> Rotation {
    match value {
        "R0" => Rotation::R0,
        "R90" => Rotation::R90,
        "R180" => Rotation::R180,
        "R270" => Rotation::R270,
        other => panic!("unexpected rotation {other}"),
    }
}

fn params_from_slice(values: &[f64]) -> PairCopulaParams {
    match values {
        [single] => PairCopulaParams::One(*single),
        [first, second] => PairCopulaParams::Two(*first, *second),
        other => panic!("unexpected parameter vector {other:?}"),
    }
}

/// Builds the rscopulas spec that represents R's estimate. The only
/// non-trivial mapping is a negative Frank parameter, which is represented
/// through its exact 90-degree rotation.
fn spec_for_r_estimate(fixture: &PairFitFixture) -> PairCopulaSpec {
    let family = parse_family(&fixture.family);
    let rotation = parse_rotation(&fixture.rotation);
    if family == PairCopulaFamily::Frank && fixture.r_params[0] < 0.0 {
        assert_eq!(rotation, Rotation::R0);
        return PairCopulaSpec {
            family,
            rotation: Rotation::R90,
            params: PairCopulaParams::One(-fixture.r_params[0]),
        };
    }
    PairCopulaSpec {
        family,
        rotation,
        params: params_from_slice(&fixture.r_params),
    }
}

fn loglik_of(spec: &PairCopulaSpec, u1: &[f64], u2: &[f64]) -> f64 {
    u1.iter()
        .zip(u2.iter())
        .map(|(&a, &b)| {
            spec.log_pdf(a, b, CLIP_EPS)
                .unwrap_or_else(|err| panic!("{spec:?} should evaluate at ({a}, {b}): {err}"))
        })
        .sum()
}

/// Maps the observed pair into the base orientation of `rotation`, mirroring
/// the crate's internal `rotated::transform_sample`.
fn to_base_orientation(rotation: Rotation, u1: &[f64], u2: &[f64]) -> (Vec<f64>, Vec<f64>) {
    let (x, y): (Vec<f64>, Vec<f64>) = u1
        .iter()
        .zip(u2.iter())
        .map(|(&a, &b)| match rotation {
            Rotation::R0 => (a, b),
            Rotation::R90 => (1.0 - a, b),
            Rotation::R180 => (1.0 - a, 1.0 - b),
            Rotation::R270 => (a, 1.0 - b),
        })
        .unzip();
    (x, y)
}

/// (c) kernels: the Rust density at R's estimate reproduces R's loglik.
fn check_kernel_reproduces_r_loglik(name: &str) {
    let fixture = load_fixture(name);
    let spec = spec_for_r_estimate(&fixture);
    spec.validate()
        .expect("R estimate should be a valid rscopulas spec");

    let loglik = loglik_of(&spec, &fixture.u1, &fixture.u2);
    assert!(
        (loglik - fixture.r_loglik).abs() < KERNEL_TOL,
        "{}: Rust loglik at R's estimate {loglik} differs from R's {} by {:e} (spec {spec:?})",
        fixture.case,
        fixture.r_loglik,
        loglik - fixture.r_loglik
    );

    // The empirical Kendall tau is a by-product every fitter relies on; it
    // must agree with R's `cor(method = "kendall")` (no ties in the data).
    let tau = rscopulas::stats::kendall_tau_bivariate(&fixture.u1, &fixture.u2)
        .expect("kendall tau should evaluate");
    assert!(
        (tau - fixture.empirical_tau).abs() < 1e-12,
        "{}: Kendall tau {tau} differs from R's {}",
        fixture.case,
        fixture.empirical_tau
    );
}

/// Signed representation of a fitted spec's parameter vector, so that a
/// Frank fit expressed either as `(R0, theta < 0)` or as `(R90/R270,
/// |theta|)` compares against the signed VineCopula parameter.
fn comparable_params(fixture: &PairFitFixture, spec: &PairCopulaSpec) -> Vec<f64> {
    let values = spec.flat_parameters();
    if spec.family == PairCopulaFamily::Frank
        && fixture.r_params[0] < 0.0
        && matches!(spec.rotation, Rotation::R90 | Rotation::R270)
    {
        return vec![-values[0]];
    }
    values
}

/// (a) + (b): the fitter reaches R's MLE.
fn check_fitter_matches_r_mle(name: &str) {
    let fixture = load_fixture(name);
    let family = parse_family(&fixture.family);
    let rotation = parse_rotation(&fixture.rotation);

    let options = VineFitOptions {
        family_set: vec![family],
        include_rotations: false,
        ..VineFitOptions::default()
    };
    let (x1, x2) = to_base_orientation(rotation, &fixture.u1, &fixture.u2);
    let fit = fit_pair_copula(&x1, &x2, &options)
        .unwrap_or_else(|err| panic!("{}: pair fit should succeed: {err}", fixture.case));
    assert_eq!(fit.spec.family, family, "{}: family", fixture.case);

    // Re-attach the fixture rotation and confirm the rotated spec on the
    // original data reproduces the fitter's own log-likelihood.
    let rotation_for_spec = if fit.spec.rotation == Rotation::R0 {
        rotation
    } else {
        fit.spec.rotation
    };
    let spec = PairCopulaSpec {
        family: fit.spec.family,
        rotation: rotation_for_spec,
        params: fit.spec.params.clone(),
    };
    let rust_loglik = loglik_of(&spec, &fixture.u1, &fixture.u2);
    assert!(
        (rust_loglik - fit.loglik).abs() < 1e-9 * (1.0 + fit.loglik.abs()),
        "{}: rotated spec loglik {rust_loglik} disagrees with fitter loglik {}",
        fixture.case,
        fit.loglik
    );

    // (a) likelihood: never more than LOGLIK_BUDGET nats below R's MLE.
    assert!(
        rust_loglik >= fixture.r_loglik - LOGLIK_BUDGET,
        "{}: Rust loglik {rust_loglik} is {} nats below R's MLE {} (Rust {:?}, R params {:?})",
        fixture.case,
        fixture.r_loglik - rust_loglik,
        fixture.r_loglik,
        spec.params,
        fixture.r_params
    );

    // (b) parameters: within max(3 SE, PARAM_FLOOR) of R's estimate.
    let rust_params = comparable_params(&fixture, &spec);
    assert_eq!(
        rust_params.len(),
        fixture.r_params.len(),
        "{}",
        fixture.case
    );
    for (idx, ((rust, r), se)) in rust_params
        .iter()
        .zip(fixture.r_params.iter())
        .zip(fixture.r_se.iter())
        .enumerate()
    {
        let tolerance = (3.0 * se).max(PARAM_FLOOR);
        assert!(
            (rust - r).abs() <= tolerance,
            "{}: parameter {idx} Rust={rust} R={r} |diff|={} > max(3*{se}, {PARAM_FLOOR})={tolerance}",
            fixture.case,
            (rust - r).abs()
        );
    }
}

macro_rules! pair_fit_cases {
    ($( $(#[$meta:meta])* $name:ident => $file:literal; )+) => {
        mod kernel_at_r_estimate {
            $(
                #[test]
                fn $name() {
                    super::check_kernel_reproduces_r_loglik($file);
                }
            )+
        }

        mod fitter_matches_r_mle {
            $(
                $(#[$meta])*
                #[test]
                fn $name() {
                    super::check_fitter_matches_r_mle($file);
                }
            )+
        }
    };
}

pair_fit_cases! {
    gaussian => "pair_fit_gaussian.json";
    gaussian_neg => "pair_fit_gaussian_neg.json";
    student_t => "pair_fit_student_t.json";
    clayton => "pair_fit_clayton.json";
    clayton_rot90 => "pair_fit_clayton_rot90.json";
    clayton_rot180 => "pair_fit_clayton_rot180.json";
    clayton_rot270 => "pair_fit_clayton_rot270.json";
    gumbel => "pair_fit_gumbel.json";
    gumbel_rot90 => "pair_fit_gumbel_rot90.json";
    gumbel_rot180 => "pair_fit_gumbel_rot180.json";
    gumbel_rot270 => "pair_fit_gumbel_rot270.json";
    frank => "pair_fit_frank.json";
    #[ignore = "pending MLE fitting (sibling branch): Frank cannot take theta < 0, so fit_pair_copula(family_set=[Frank]) fails with 'pair-copula selection produced no candidate' on negative-dependence data (R MLE theta = -3.898, n = 2000)"]
    frank_neg => "pair_fit_frank_neg.json";
    joe => "pair_fit_joe.json";
    joe_rot90 => "pair_fit_joe_rot90.json";
    joe_rot180 => "pair_fit_joe_rot180.json";
    joe_rot270 => "pair_fit_joe_rot270.json";
    #[ignore = "pending true 2-parameter MLE: the BB1 fitter snaps delta to the grid {1.05,1.25,1.5,2,3,5}; Rust (theta, delta) = (0.779, 2.0) vs R MLE (0.985, 1.781), loglik 7.77 nats below R at n = 2000"]
    bb1 => "pair_fit_bb1.json";
    #[ignore = "pending true 2-parameter MLE: the BB1 fitter snaps delta to the grid {1.05,1.25,1.5,2,3,5}; Rust (theta, delta) = (0.843, 2.0) vs R MLE (1.024, 1.813), loglik 5.50 nats below R at n = 2000"]
    bb1_rot90 => "pair_fit_bb1_rot90.json";
    #[ignore = "pending true 2-parameter MLE: the BB1 fitter snaps delta to the grid {1.05,1.25,1.5,2,3,5}; Rust (theta, delta) = (0.747, 2.0) vs R MLE (0.974, 1.761), loglik 9.60 nats below R at n = 2000"]
    bb1_rot180 => "pair_fit_bb1_rot180.json";
    #[ignore = "pending true 2-parameter MLE: the BB1 fitter snaps delta to the grid {1.05,1.25,1.5,2,3,5}; Rust (theta, delta) = (0.932, 2.0) vs R MLE (1.060, 1.871), loglik 2.54 nats below R at n = 2000"]
    bb1_rot270 => "pair_fit_bb1_rot270.json";
    bb6 => "pair_fit_bb6.json";
    #[ignore = "pending true 2-parameter MLE: the BB6 fitter snaps delta to the grid {1.05,1.25,1.5,2,3,5}; Rust (theta, delta) = (2.015, 1.5) vs R MLE (1.773, 1.660), loglik 1.06 nats below R at n = 2000"]
    bb6_rot90 => "pair_fit_bb6_rot90.json";
    bb6_rot180 => "pair_fit_bb6_rot180.json";
    #[ignore = "pending true 2-parameter MLE: the BB6 fitter snaps delta to the grid {1.05,1.25,1.5,2,3,5}; Rust (theta, delta) = (1.324, 2.0) vs R MLE (1.484, 1.837), loglik 0.84 nats below R at n = 2000"]
    bb6_rot270 => "pair_fit_bb6_rot270.json";
    #[ignore = "pending true 2-parameter MLE: the BB7 fitter snaps delta to the grid {0.25,0.5,1,2,4,8}; Rust (theta, delta) = (1.564, 1.0) vs R MLE (1.471, 1.453), loglik 28.2 nats below R at n = 2000"]
    bb7 => "pair_fit_bb7.json";
    #[ignore = "pending true 2-parameter MLE: the BB7 fitter snaps delta to the grid {0.25,0.5,1,2,4,8}; Rust (theta, delta) = (1.711, 1.0) vs R MLE (1.609, 1.482), loglik 29.6 nats below R at n = 2000"]
    bb7_rot90 => "pair_fit_bb7_rot90.json";
    #[ignore = "pending true 2-parameter MLE: the BB7 fitter snaps delta to the grid {0.25,0.5,1,2,4,8}; Rust (theta, delta) = (1.464, 2.0) vs R MLE (1.502, 1.511), loglik 27.9 nats below R at n = 2000"]
    bb7_rot180 => "pair_fit_bb7_rot180.json";
    #[ignore = "pending true 2-parameter MLE: the BB7 fitter snaps delta to the grid {0.25,0.5,1,2,4,8}; Rust (theta, delta) = (1.421, 2.0) vs R MLE (1.455, 1.520), loglik 28.9 nats below R at n = 2000"]
    bb7_rot270 => "pair_fit_bb7_rot270.json";
    bb8 => "pair_fit_bb8.json";
    bb8_rot90 => "pair_fit_bb8_rot90.json";
    #[ignore = "pending true 2-parameter MLE: the BB8 fitter snaps delta to the grid {0.1,0.3,0.5,0.7,0.9,1-1e-6}; Rust (theta, delta) = (1.709, 0.9) vs R MLE (1.931, 0.831), loglik 0.90 nats below R at n = 2000"]
    bb8_rot180 => "pair_fit_bb8_rot180.json";
    #[ignore = "pending true 2-parameter MLE: the BB8 fitter snaps delta to the grid {0.1,0.3,0.5,0.7,0.9,1-1e-6}; Rust (theta, delta) = (1.672, 0.9) vs R MLE (1.830, 0.847), loglik 0.55 nats below R at n = 2000"]
    bb8_rot270 => "pair_fit_bb8_rot270.json";
    #[ignore = "pending true 2-parameter MLE: the Tawn fitter snaps the shape to the grid {0.1,0.3,0.5,0.7,0.9,1-1e-6}; Rust (theta, alpha) = (2.128, 0.5) vs R MLE (2.088, 0.531), loglik 1.65 nats below R at n = 2000"]
    tawn1 => "pair_fit_tawn1.json";
    #[ignore = "pending true 2-parameter MLE: the Tawn fitter snaps the shape to the grid {0.1,0.3,0.5,0.7,0.9,1-1e-6}; Rust (theta, shape) = (1.887, 0.7) vs R MLE (2.066, 0.544), loglik 2.89 nats below R at n = 2000"]
    tawn1_rot90 => "pair_fit_tawn1_rot90.json";
    #[ignore = "pending true 2-parameter MLE: the Tawn fitter snaps the shape to the grid {0.1,0.3,0.5,0.7,0.9,1-1e-6}; Rust alpha = 0.7 vs R MLE 0.542 (|diff| 0.158 > 3 SE = 0.086) at n = 2000"]
    tawn1_rot180 => "pair_fit_tawn1_rot180.json";
    #[ignore = "pending true 2-parameter MLE: the Tawn fitter snaps the shape to the grid {0.1,0.3,0.5,0.7,0.9,1-1e-6}; Rust (theta, shape) = (1.898, 0.7) vs R MLE (2.067, 0.555), loglik 1.63 nats below R at n = 2000"]
    tawn1_rot270 => "pair_fit_tawn1_rot270.json";
    #[ignore = "pending true 2-parameter MLE: the Tawn fitter snaps the shape to the grid {0.1,0.3,0.5,0.7,0.9,1-1e-6}; Rust (theta, beta) = (2.144, 0.5) vs R MLE (2.086, 0.549), loglik 4.57 nats below R at n = 2000"]
    tawn2 => "pair_fit_tawn2.json";
    #[ignore = "pending true 2-parameter MLE: the Tawn fitter snaps the shape to the grid {0.1,0.3,0.5,0.7,0.9,1-1e-6}; Rust shape = 0.7 vs R MLE 0.569 (|diff| 0.131 > 3 SE = 0.079) at n = 2000"]
    tawn2_rot90 => "pair_fit_tawn2_rot90.json";
    #[ignore = "pending true 2-parameter MLE: the Tawn fitter snaps the shape to the grid {0.1,0.3,0.5,0.7,0.9,1-1e-6}; Rust (theta, beta) = (2.152, 0.5) vs R MLE (2.099, 0.539), loglik 2.48 nats below R at n = 2000"]
    tawn2_rot180 => "pair_fit_tawn2_rot180.json";
    #[ignore = "pending true 2-parameter MLE: the Tawn fitter snaps the shape to the grid {0.1,0.3,0.5,0.7,0.9,1-1e-6}; Rust (theta, shape) = (1.865, 0.7) vs R MLE (2.023, 0.557), loglik 2.29 nats below R at n = 2000"]
    tawn2_rot270 => "pair_fit_tawn2_rot270.json";
}
