//! Cross-validation of `VineCopula::fit_c_vine_with_order` against
//! VineCopula's `RVineSeqEst(method = "mle")` on the same C-vine structure.
//!
//! Fixtures: `fixtures/reference/fits/v1/cvine_fit_*.json`, generated by
//! `scripts/reference/generate_fit_fixtures.R`. Each fixture simulates
//! `n = 2000` rows from a 4- or 5-dimensional C-vine with a fixed variable
//! order and a single family (Gaussian, or Clayton with a rotation chosen per
//! edge by R), re-estimates every pair-copula parameter sequentially with
//! `RVineSeqEst` on the *same* structure and family matrix, and stores the
//! data, R's per-edge estimates and standard errors, and the total
//! log-likelihood.
//!
//! # Order / anchor mapping
//!
//! R's `C2RVine(order)` makes `order[1]` the root of tree 1, `order[2]` the
//! root of tree 2, and so on; the fixture stores that order both 1-based
//! (`r_order`) and 0-based (`order`). rscopulas' `fit_c_vine_with_order`
//! uses `order[k]` as the root of tree `k + 1` in the same way, so the
//! 0-based order is passed through unchanged. The last element `order[d - 1]`
//! is the only variable that is never a root; it becomes
//! `variable_order()[0]`, the Rosenblatt anchor, which the tests assert.
//!
//! # Edge orientation
//!
//! VineCopula evaluates the pair-copula in matrix cell `(i, j)` as
//! `C(u_M[i,j], u_M[j,j])`; for a C-vine `M[i, j]` is the tree root, so R's
//! edges are oriented `(root, other)` exactly like rscopulas' C-vine edges
//! `conditioned = (root, other)`. The test nevertheless matches edges by
//! their unordered conditioned/conditioning sets and applies `swap_axes`
//! whenever the orientation differs, so it does not rely on that fact.
//!
//! # Checks
//!
//! * `structure_and_params`: rebuilding R's fitted vine with `from_trees`
//!   reproduces R's total log-likelihood to `1e-6` (this validates the
//!   structure/orientation/rotation mapping independent of the fitter);
//!   every fitted edge has the same family and rotation as R, and its
//!   parameter is within `max(3 * SE, 0.02)` of R's estimate where `SE` is
//!   the inverse-observed-information standard error reported by
//!   `RVineSeqEst(se = TRUE)`.
//! * `loglik_matches_r_mle`: the Rust fit's `diagnostics.loglik` is at most
//!   `0.5` nats below R's sequential MLE.

use std::{fs, path::PathBuf};

use ndarray::Array2;
use serde::Deserialize;

use rscopulas::{
    CopulaModel, EvalOptions, PairCopulaFamily, PairCopulaParams, PairCopulaSpec, PseudoObs,
    Rotation, VineCopula, VineEdge, VineFitOptions, VineStructureKind, VineTree,
};

const LOGLIK_BUDGET: f64 = 0.5;
const STRUCTURE_TOL: f64 = 1e-6;
const PARAM_FLOOR: f64 = 0.02;

#[allow(dead_code)]
#[derive(Debug, Deserialize)]
struct Metadata {
    source_package: String,
    source_version: String,
}

#[allow(dead_code)]
#[derive(Debug, Deserialize)]
struct EdgeFixture {
    tree: usize,
    conditioned: [usize; 2],
    conditioning: Vec<usize>,
    family_code: i32,
    family: String,
    rotation: String,
    true_par: f64,
    true_params: Vec<f64>,
    r_par: f64,
    r_par2: f64,
    r_params: Vec<f64>,
    r_se: Vec<f64>,
    r_pair_loglik: f64,
}

#[allow(dead_code)]
#[derive(Debug, Deserialize)]
struct CvineFitFixture {
    metadata: Metadata,
    case: String,
    kind: String,
    dim: usize,
    n: usize,
    r_order: Vec<usize>,
    order: Vec<usize>,
    r_loglik: f64,
    edges: Vec<EdgeFixture>,
    data: Vec<Vec<f64>>,
}

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/reference/fits/v1")
}

fn load_fixture(name: &str) -> CvineFitFixture {
    let path = fixture_dir().join(name);
    let bytes =
        fs::read(&path).unwrap_or_else(|err| panic!("fixture {path:?} should exist: {err}"));
    let fixture: CvineFitFixture =
        serde_json::from_slice(&bytes).expect("fixture should deserialize");
    assert_eq!(fixture.metadata.source_package, "VineCopula");
    assert_eq!(fixture.data.len(), fixture.n);
    assert_eq!(fixture.order.len(), fixture.dim);
    assert_eq!(fixture.edges.len(), fixture.dim * (fixture.dim - 1) / 2);
    for (zero_based, one_based) in fixture.order.iter().zip(fixture.r_order.iter()) {
        assert_eq!(
            zero_based + 1,
            *one_based,
            "order must be R's order minus one"
        );
    }
    fixture
}

fn parse_family(value: &str) -> PairCopulaFamily {
    match value {
        "Gaussian" => PairCopulaFamily::Gaussian,
        "Clayton" => PairCopulaFamily::Clayton,
        other => panic!("unexpected family {other}"),
    }
}

fn parse_rotation(value: &str) -> Rotation {
    match value {
        "R0" => Rotation::R0,
        "R90" => Rotation::R90,
        "R180" => Rotation::R180,
        "R270" => Rotation::R270,
        other => panic!("unexpected rotation {other}"),
    }
}

fn params_from_slice(values: &[f64]) -> PairCopulaParams {
    match values {
        [single] => PairCopulaParams::One(*single),
        [first, second] => PairCopulaParams::Two(*first, *second),
        other => panic!("unexpected parameter vector {other:?}"),
    }
}

fn r_spec(edge: &EdgeFixture) -> PairCopulaSpec {
    PairCopulaSpec {
        family: parse_family(&edge.family),
        rotation: parse_rotation(&edge.rotation),
        params: params_from_slice(&edge.r_params),
    }
}

fn array2(rows: &[Vec<f64>]) -> Array2<f64> {
    let nrows = rows.len();
    let ncols = rows.first().map_or(0, Vec::len);
    let data = rows
        .iter()
        .flat_map(|row| row.iter().copied())
        .collect::<Vec<_>>();
    Array2::from_shape_vec((nrows, ncols), data).expect("rows should form a matrix")
}

/// Rebuilds R's fitted model as rscopulas trees, keeping R's `(root, other)`
/// edge orientation.
fn r_fitted_model(fixture: &CvineFitFixture) -> VineCopula {
    let mut trees = Vec::with_capacity(fixture.dim - 1);
    for level in 1..fixture.dim {
        let edges = fixture
            .edges
            .iter()
            .filter(|edge| edge.tree == level)
            .map(|edge| VineEdge {
                tree: level,
                conditioned: (edge.conditioned[0], edge.conditioned[1]),
                conditioning: edge.conditioning.clone(),
                copula: r_spec(edge),
            })
            .collect::<Vec<_>>();
        assert_eq!(edges.len(), fixture.dim - level, "tree {level} edge count");
        trees.push(VineTree { level, edges });
    }
    VineCopula::from_trees(VineStructureKind::C, trees, None)
        .expect("R's fitted C-vine should be a valid rscopulas vine")
}

fn fit_options(fixture: &CvineFitFixture) -> VineFitOptions {
    let family = match fixture.kind.as_str() {
        "gaussian" => PairCopulaFamily::Gaussian,
        "clayton" => PairCopulaFamily::Clayton,
        other => panic!("unexpected fixture kind {other}"),
    };
    VineFitOptions {
        family_set: vec![family],
        // Gaussian only has R0; Clayton must be free to pick the rotation R
        // used for the simulation (the fitter restricts candidates by the
        // sign of Kendall's tau and then compares AIC).
        include_rotations: true,
        ..VineFitOptions::default()
    }
}

fn sorted(values: &[usize]) -> Vec<usize> {
    let mut out = values.to_vec();
    out.sort_unstable();
    out
}

fn find_rust_edge<'a>(model: &'a VineCopula, edge: &EdgeFixture) -> (&'a VineEdge, bool) {
    let tree = &model.trees()[edge.tree - 1];
    assert_eq!(tree.level, edge.tree);
    let wanted = sorted(&edge.conditioned);
    let wanted_conditioning = sorted(&edge.conditioning);
    for candidate in &tree.edges {
        let candidate_pair = sorted(&[candidate.conditioned.0, candidate.conditioned.1]);
        if candidate_pair == wanted && sorted(&candidate.conditioning) == wanted_conditioning {
            let same_orientation = candidate.conditioned.0 == edge.conditioned[0];
            return (candidate, same_orientation);
        }
    }
    panic!(
        "no rscopulas edge matches R edge {:?} | {:?} in tree {}",
        edge.conditioned, edge.conditioning, edge.tree
    );
}

fn check_structure_and_params(name: &str) {
    let fixture = load_fixture(name);
    let data = PseudoObs::new(array2(&fixture.data)).expect("fixture data should be valid");

    // Structure/orientation mapping check, independent of the fitter: R's
    // fitted parameters plugged into rscopulas' vine reproduce R's loglik.
    let r_model = r_fitted_model(&fixture);
    let r_loglik_in_rust: f64 = r_model
        .log_pdf(&data, &EvalOptions::default())
        .expect("R model log pdf should evaluate")
        .iter()
        .sum();
    assert!(
        (r_loglik_in_rust - fixture.r_loglik).abs() < STRUCTURE_TOL,
        "{}: rscopulas evaluation of R's fitted vine gives {r_loglik_in_rust}, R reports {} (diff {:e})",
        fixture.case,
        fixture.r_loglik,
        r_loglik_in_rust - fixture.r_loglik
    );
    assert_eq!(
        r_model.variable_order()[0],
        fixture.order[fixture.dim - 1],
        "{}: order[d-1] must be the Rosenblatt anchor",
        fixture.case
    );

    let fit = VineCopula::fit_c_vine_with_order(&data, &fixture.order, &fit_options(&fixture))
        .unwrap_or_else(|err| panic!("{}: C-vine fit should succeed: {err}", fixture.case));
    let model = &fit.model;
    assert_eq!(model.structure(), VineStructureKind::C);
    assert_eq!(
        model.order(),
        fixture.order,
        "{}: C-vine order",
        fixture.case
    );
    assert_eq!(
        model.variable_order()[0],
        fixture.order[fixture.dim - 1],
        "{}: order[d-1] must be the Rosenblatt anchor",
        fixture.case
    );

    for edge in &fixture.edges {
        let (rust_edge, same_orientation) = find_rust_edge(model, edge);
        let expected = if same_orientation {
            r_spec(edge)
        } else {
            r_spec(edge).swap_axes()
        };
        let actual = &rust_edge.copula;
        assert_eq!(
            actual.family, expected.family,
            "{}: family on edge {:?} | {:?}",
            fixture.case, edge.conditioned, edge.conditioning
        );
        assert_eq!(
            actual.rotation, expected.rotation,
            "{}: rotation on edge {:?} | {:?} (R code {}, R par {}, Rust {:?})",
            fixture.case, edge.conditioned, edge.conditioning, edge.family_code, edge.r_par, actual
        );
        let actual_params = actual.flat_parameters();
        let expected_params = expected.flat_parameters();
        assert_eq!(actual_params.len(), expected_params.len());
        for (idx, ((rust, r), se)) in actual_params
            .iter()
            .zip(expected_params.iter())
            .zip(edge.r_se.iter())
            .enumerate()
        {
            let tolerance = (3.0 * se).max(PARAM_FLOOR);
            assert!(
                (rust - r).abs() <= tolerance,
                "{}: edge {:?} | {:?} parameter {idx}: Rust={rust} R={r} |diff|={} > max(3*{se}, {PARAM_FLOOR})={tolerance}",
                fixture.case,
                edge.conditioned,
                edge.conditioning,
                (rust - r).abs()
            );
        }
    }
}

fn check_loglik_matches_r_mle(name: &str) {
    let fixture = load_fixture(name);
    let data = PseudoObs::new(array2(&fixture.data)).expect("fixture data should be valid");
    let fit = VineCopula::fit_c_vine_with_order(&data, &fixture.order, &fit_options(&fixture))
        .unwrap_or_else(|err| panic!("{}: C-vine fit should succeed: {err}", fixture.case));

    let recomputed: f64 = fit
        .model
        .log_pdf(&data, &EvalOptions::default())
        .expect("fitted vine log pdf should evaluate")
        .iter()
        .sum();
    assert!(
        (recomputed - fit.diagnostics.loglik).abs() < 1e-9 * (1.0 + fit.diagnostics.loglik.abs()),
        "{}: diagnostics.loglik {} disagrees with sum(log_pdf) {recomputed}",
        fixture.case,
        fit.diagnostics.loglik
    );
    assert!(
        fit.diagnostics.loglik >= fixture.r_loglik - LOGLIK_BUDGET,
        "{}: Rust loglik {} is {} nats below R's sequential MLE {}",
        fixture.case,
        fit.diagnostics.loglik,
        fixture.r_loglik - fit.diagnostics.loglik,
        fixture.r_loglik
    );
}

macro_rules! cvine_fit_cases {
    ($( $(#[$meta:meta])* $name:ident => $file:literal; )+) => {
        mod structure_and_params {
            $(
                #[test]
                fn $name() {
                    super::check_structure_and_params($file);
                }
            )+
        }

        mod loglik_matches_r_mle {
            $(
                $(#[$meta])*
                #[test]
                fn $name() {
                    super::check_loglik_matches_r_mle($file);
                }
            )+
        }
    };
}

cvine_fit_cases! {
    #[ignore = "pending MLE fitting (sibling branch): the Gaussian pair fit is tau inversion, so the sequential C-vine fit is 0.61 nats below R's sequential MLE at n = 2000 (6 edges)"]
    gaussian_d4 => "cvine_fit_gaussian_d4.json";
    #[ignore = "pending MLE fitting (sibling branch): the Gaussian pair fit is tau inversion, so the sequential C-vine fit is 2.28 nats below R's sequential MLE at n = 2000 (10 edges)"]
    gaussian_d5 => "cvine_fit_gaussian_d5.json";
    clayton_d4 => "cvine_fit_clayton_d4.json";
    clayton_d5 => "cvine_fit_clayton_d5.json";
}
